### ISSUE TITLE
[Bug] Pug error in dependency requires restart of webpack

### ISSUE THREAD

**Issue by XenoBino** [webdiscus/pug-loader#14] opened 2022-05-10 09:20 UTC
I am facing a non reproducible issue where:
```
  [pug-loader] Pug compilation failed.
  Error: Error parsing body of the with expression
```
Doesn't go even if I comment the whole file. It requires me to restart the webpack dev server instance. My build is CPU intensive. It takes about half a minute to have something on the screen and caching is not working properly. I have to wait half a minute every time a pug error occurs. And pug errors are extremely unreadable. Making it even harder to fix the pug error.

**Comment by webdiscus** [comment] 2022-05-10 11:23
Hello @XenoBino,

thank You for the report.

1. I need to see your webpack.config.js and pug template.
2. Are you using the `self` option of the pug loader? Is it enabled?
3. Does the error occur in build mode: `webpack --mode=production`, not with serv?

**Comment by m10** [comment] 2022-05-11 12:52
i get that error too when there is e.g. a syntax error in a javascript snippet in the pug template.
I agree that the error message is most unhelpful.

the overall problem with error handling ("requires restart") seems to be that the loader / pug can't resolve the dependencies anymore an thus webpack does not watch the files anymore. Only the entrypoint is still being watched, saving that one will trigger a rebuild. One has to know that though.

Other loaders have / had this problem too. E.g. simlpe-pug-loader adds at least the file where the error happened, even if not ideal it does help. A mechanism to remember the dependencies and keep watching them on error would be ideal though.

https://github.com/Spence-S/simple-pug-loader/issues/10

**Comment by webdiscus** [comment] 2022-05-11 13:01
@m10 Thanks for explaining the problem. This helps me to start researching the problem.

**Comment by m10** [comment] 2022-05-11 13:24
I checked the source and @webdiscus/pug-loader does in fact add the error file as dependency. For some reason this does not seem to work for this kind of error. Maybe because pug does not return any filename in this case..

https://github.com/webdiscus/pug-loader/blob/b43003272296f8802afb695f02dc059323aa837f/src/index.js#L167

**Comment by webdiscus** [comment] 2022-05-11 13:53
> I checked the source and @webdiscus/pug-loader does in fact add the error file as dependency. For some reason this does not seem to work for this kind of error. Maybe pug does not return any filename in this case..
> 
> https://github.com/webdiscus/pug-loader/blob/b43003272296f8802afb695f02dc059323aa837f/src/index.js#L167

Could you please show your short snippets of Pug:
- the snippet works correctly
- the same snippet contained a Pug error that is causing this issue

**Comment by webdiscus** [comment] 2022-05-18 10:41
@m10 @XenoBino 
do you can please share any invalid Pug code which generates the error `Error parsing body of the with expression`?

I can't reproduce it.

**Comment by webdiscus** [comment] 2022-05-18 22:21
@XenoBino @m10 

the issue is fixed in version `2.2.1`.
Do you can please test it and give a feedback whether the problem is solved?

**Closed** 2022-05-24 08:52 UTC

**Comment by m10** [comment] 2022-05-25 09:01
@webdiscus i can confirm that the newest version `2.3.0` recovers correctly from JS syntax errors.

The error message ist still confusing though. Should that be tracked in a separate issue?

**Comment by webdiscus** [comment] 2022-05-25 11:10
> @webdiscus i can confirm that the newest version `2.3.0` recovers correctly from JS syntax errors.
> 
> The error message ist still confusing though. Should that be tracked in a separate issue?

Yes, please new issue/enhancement create in a separate issue.
